mk_oracle-2014.09.23_1.2.2p0_tbr.mkp

diff --git a/mk_oracle/mk_oracle/agents/plugins/mk_oracle b/mk_oracle/mk_oracle/agents/plugins/mk_oracle
--- a/mk_oracle/mk_oracle/agents/plugins/mk_oracle
+++ b/mk_oracle/mk_oracle/agents/plugins/mk_oracle
@@ -6,7 +6,7 @@
 # |           | |___| | | |  __/ (__|   <    | |  | | . \            |
 # |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
 # |                                                                  |
-# | Copyright Mathias Kettner 2013             mk@mathias-kettner.de |
+# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
 # +------------------------------------------------------------------+
 #
 # This file is part of Check_MK.
@@ -29,7 +29,9 @@
 # stuff, Mathias for the shell hacking...
 
 # Example for mk_oracle.cfg
-# DBUSER=<DBUSER>:<PASSWORD>:<SYSDBA/SYSASM>:<HOSTNAME>:<Port>
+# DBUSER=<DBUSER>:<PASSWORD>:<SYSDBA>:<HOSTNAME>:<Port>
+# DBASM=<DBUSER>:<PASSWORD>:<SYSDBA/SYSASM>:<HOSTNAME>:<Port>
+#
 # SYSDBA or SYSASM is optional but needed for a mounted instance
 # HOSTNAME is optional - Default is localhost
 # PORT is optional - Default is 1521
@@ -759,7 +761,7 @@ function sqlplus ()
     else
         echo '<<<oracle_instance:sep(124)>>>'
         local SID_UPPER=$(echo "$SID" | tr '[:lower:]' '[:upper:]')
-        echo "$OUTPUT" | sed -r -e "/^(ERROR:)?$/d" | tr '\n' ' ' | sed "s/^/$SID_UPPER|FAILURE|/" ; echo
+        echo "$OUTPUT" | grep -v "^ERROR at line" | tr '\n' ' ' | sed "s/^/$SID_UPPER|FAILURE|/" ; echo
         return 1
     fi
 }
@@ -845,7 +847,7 @@ function run_cached_local () {
     # Cache file outdated and new job not yet running? Start it
     if [ -z "$USE_CACHEFILE" -a ! -e "$CACHEFILE.new" ] ; then
         if [ $DEBUG -eq 1 ] ; then
-            echo "set -o noclobber ; exec > \"$CACHEFILE.new\" || exit 1 ; $CMDLINE && mv \"$CACHEFILE.new\" \"$CACHEFILE\" || rm -f \"$CACHEFILE\" \"$CACHEFILE.new\"" | bash 
+            echo "set -o noclobber ; exec > \"$CACHEFILE.new\" || exit 1 ; $CMDLINE && mv \"$CACHEFILE.new\" \"$CACHEFILE\" || rm -f \"$CACHEFILE\" \"$CACHEFILE.new\"" | bash
         else
             echo "set -o noclobber ; exec > \"$CACHEFILE.new\" || exit 1 ; $CMDLINE && mv \"$CACHEFILE.new\" \"$CACHEFILE\" || rm -f \"$CACHEFILE\" \"$CACHEFILE.new\"" | nohup bash 2>/dev/null &
         fi
